spring:
  application:
    name: jobs-api
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_REST_PORT:9200}

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    clientId: ${OKTA_CLIENT_ID}
    rolesClaim: groups

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

app:
  cors:
    allowed-origins: "*"
  number-of-fake-jobs: 100

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
